version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: demo_zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - my_master_slave_sql

  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: demo_kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
      - my_master_slave_sql

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo_kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: demo_kafka:9092
    ports:
      - "9089:8080"
    links:
      - kafka
    networks:
      - my_master_slave_sql

  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    container_name: demo_connect
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - DATABASE_HOSTNAME=mysql8-master  # Kết nối đến container MySQL hiện có
     - DATABASE_PORT=3306                 # Cổng MySQL
     - DATABASE_USER=root                 # Tài khoản MySQL
     - DATABASE_PASSWORD=123456           # Mật khẩu MySQL
     - DATABASE_NAME=test                  # Tên database
    networks:
      - my_master_slave_sql

networks:
  my_master_slave_sql:
    external: true  # Chỉ định rằng mạng này đã tồn tại bên ngoài
