version: '3'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    container_name: demo_zookeeper
    ports:
     - 2181:2181
    networks:
      - my_master_slave_sql

  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    container_name: demo_kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_CONNECT: demo_zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - my_master_slave_sql

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: demo_kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: demo_kafka:29092
    ports:
      - "9089:8080"
    links:
      - kafka
    networks:
      - my_master_slave_sql

  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    container_name: demo_connect
    ports:
     - 8083:8083
    links:
     - kafka
    environment:
     - BOOTSTRAP_SERVERS=demo_kafka:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - DATABASE_HOSTNAME=mysql8-master  # Kết nối tới MySQL đã cài
     - DATABASE_PORT=3306
     - DATABASE_USER=root
     - DATABASE_PASSWORD=123456
     - DATABASE_NAME=test
    networks:
      - my_master_slave_sql

networks:
  my_master_slave_sql:
    external: true
