server:
  port: 
  mode: "dev"
mysql_haproxy: 
  host: 127.0.0.1
  port: 3369
  username: haproxy_check
  password: 123456
  dbname: test
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 3600
# mysql_slave: 
#   host: 127.0.0.1
#   port: 8822
#   username: root
#   password: 123456
#   dbname: test
#   maxIdleConns: 10
#   maxOpenConns: 100
#   connMaxLifetime: 3600
# mysql_slave2: 
#   host: 127.0.0.1
#   port: 8823
#   username: root
#   password: 123456
#   dbname: test
#   maxIdleConns: 10
#   maxOpenConns: 100
#   connMaxLifetime: 3600
# mysql_slave3: 
#   host: 127.0.0.1
#   port: 8824
#   username: root
#   password: 123456
#   dbname: test
#   maxIdleConns: 10
#   maxOpenConns: 100
#   connMaxLifetime: 3600
log:
  log_level: debug
  file_log_name: ./storages/logs/dev.xxx.log
  max_size: 500
  max_backups: 3
  max_age: 28
  compress: true
kafka:
  brokers: localhost:9092
redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET: "xxx.yyy.zzz"
